name: app_clone_fonos
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  fluro: ^2.0.5
  provider: ^6.1.2
  equatable: ^2.0.7
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.1
  mask_text_input_formatter: ^2.0.0
  introduction_screen: ^3.1.17  # Package để tạo onboarding screen
  shared_preferences: ^2.2.3
  flutter_bloc: ^9.1.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  google_sign_in: ^6.3.0
  just_audio: ^0.9.35  # Hoặc phiên bản mới nhất
  youtube_explode_dart: ^2.4.0
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  http: ^1.4.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo_white.png
    - assets/images/background_onboarding.jpg
    - assets/images/logo_text_white.png
    - assets/images/mail_icon.png