// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATX6D-cj4VanUg693xh7mI8r6PqHt7D40',
    appId: '1:915357877849:android:5ab8ff2de847b6bc345348',
    messagingSenderId: '915357877849',
    projectId: 'flutter-login-app-3d444',
    storageBucket: 'flutter-login-app-3d444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOsiNJ17k6szv-b1O__PXsD1v12Nr4mcM',
    appId: '1:915357877849:ios:00af95e9b7aaafd0345348',
    messagingSenderId: '915357877849',
    projectId: 'flutter-login-app-3d444',
    storageBucket: 'flutter-login-app-3d444.firebasestorage.app',
    androidClientId: '915357877849-af2aj483m61h7su1h6fi83ttknoh13rg.apps.googleusercontent.com',
    iosClientId: '915357877849-iqhqtgsropr9m94mcs554mu82co1437h.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCloneFonos',
  );

}